# Generated by Django 5.0.1 on 2024-01-18 11:22

import app.utils.file_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_role_staff_delete_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='profile',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='default_images/doctor-profile.png', upload_to=app.utils.file_helpers.custom_file_name),
        ),
    ]
